# Generated by Django 6.0.7 on 2026-09-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
