# Generated by Django 6.0.7 on 2026-09-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='closed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
